
server:
  tomcat:
    max-threads: 300
  # Set the application context path for Spring MVC Dispatcher Servlet (Actuator uses Spring MVC)
  # servlet-path: /system
---


spring:
  profiles: local
logging:
  config: classpath:env/local/logback.xml
---
spring:
  profiles: cloud
logging:
  config: classpath:env/cloud/logback.xml
---

#
# Other Springboot default settings
#
management:
  health:
    db:
      enabled: false
    defaults:
      enabled: false
  security:
    enabled: false
---


endpoints:
  enabled: true
  health:
    sensitive: false
    enabled: true
  metrics:
    enabled: true
  jmx:
    enabled: true
---